### ISSUE TITLE
It is not possible to retrieve large (e.g. 100k) events from the provider service

### ISSUE THREAD

**Issue by marwinski** [gardener/falco-event-provider#36]
**What happened**:

It is not possible to retrieve large (e.g. 100k) events from the provider service. At a certain point in time i get an "unexpected status code: 502 Bad Gateway" errror.

**What you expected to happen**:

Get all the results in timely manner.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

The problem is with the `offset` feature (https://www.postgresql.org/docs/current/queries-limit.html) that we use for chunked retrieval of events. This gets very inefficient with large result sets.

**Environment**:

**Comment by lsroe** [comment]
provided in https://github.com/gardener/falco-event-provider/pull/37
